name: cx_ra_rn
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.11
  - numpy=1.25.*
  - scipy=1.10.*
  - matplotlib=3.7.*
  - pillow=9.4.*
  - pandas
  - pip
  - pip:
    - opencv-python-headless
    - swig